# Generated by Django 6.0.7 on 2026-07-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRecordModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('pathogen', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('management', models.TextField()),
                ('technical_warning', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diagnostic_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
