# Generated by Django 6.0.7 on 2026-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticrecordmodel',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticrecordmodel',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecordmodel',
            name='user_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
