services:

  db:
    image: postgres:16

    container_name: postgres_db

    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:

    build:
      context: .

    container_name: django_backend

    env_file:
      - .env

    ports:
      - "0.0.0.0:8000:8000"

    volumes:
      - .:/app

    depends_on:
      - db

    command:
      python manage.py runserver 0.0.0.0:8000


volumes:

  postgres_data: